backend:
  name: github
  repo: GuzhengAlive/hugo-cms # Path to your GitHub repository

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "expert" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Expert" # Used in the UI, ie.: "New Post"
    folder: "site/content/guzheng-experts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Videos", name: videos, widget: list, fields: [
          {label: "Youtube Video Code", name: "youtubecode", widget: "string"}]}
  - name: "guzhengs-style" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Guzheng Style" # Used in the UI, ie.: "New Post"
    folder: "site/content/guzhengs-styles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Section", name: "section", widget: "string"}
      - {label: "Order", name: "order", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Image_Credit, name: image_credit, widget: markdown, required: false}
          - {label: "Groups", name: groups, widget: list, fields: [
              {label: "Title", name: "title", widget: "text"},
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "markdown"}]}
          - label: Sections
            name: sections
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string, required: false}
              - {label: Text, name: text, widget: markdown, required: false}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/products/_index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Image_Credit, name: image_credit, widget: markdown, required: false}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "site/content/values/_index.md"
        label: "Values Page"
        name: "values"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Image_Credit, name: image_credit, widget: markdown, required: false}
          - label: Values
            name: values
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}
      - file: "site/content/about-gza/_index.md"
        label: "About GZA"
        name: "aboutgza"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Image Credit, name: imagecredit, widget: markdown, required: false}
          - label: Sections
            name: sections
            widget: list
            fields:
            - {label: Heading, name: heading, widget: string, required: false}
            - {label: Text, name: text, widget: markdown, required: false}
      - file: "site/content/bibliography/_index.md"
        label: "Bibliography"
        name: "bibliography"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Image Credit, name: imagecredit, widget: markdown, required: false}
          - label: Sections
            name: sections
            widget: list
            fields:
            - {label: Heading, name: heading, widget: string, required: false}
            - {label: Text, name: text, widget: markdown, required: false}
      - file: "site/content/blogs-and-private-works/_index.md"
        label: "Blogs and Private Works Page"
        name: "blogs-and-private-works"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Image_Credit, name: image_credit, widget: markdown, required: false}
          - label: Blogs
            name: blogs
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: markdown}
              - {label: Image, name: imageUrl, widget: image}
              - {label: Link, name: link, widget: string}
      - file: "site/content/buy-new/_index.md"
        label: "Buy New"
        name: "buynew"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Image Credit, name: imagecredit, widget: markdown, required: false}
          - label: Sections
            name: sections
            widget: list
            fields:
            - {label: Heading, name: heading, widget: string, required: false}
            - {label: Text, name: text, widget: markdown, required: false}
      - file: "site/content/buy-used-guzheng/_index.md"
        label: "Buy Used Guzheng"
        name: "buyusedguzheng"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Image Credit, name: imagecredit, widget: markdown, required: false}
          - label: Sections
            name: sections
            widget: list
            fields:
            - {label: Heading, name: heading, widget: string, required: false}
            - {label: Text, name: text, widget: markdown, required: false}
      - file: "site/content/change-log/_index.md"
        label: "Change Log"
        name: "changelog"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Image Credit, name: imagecredit, widget: markdown, required: false}
          - label: Sections
            name: sections
            widget: list
            fields:
            - {label: Heading, name: heading, widget: string, required: false}
            - {label: Text, name: text, widget: markdown, required: false}
      - file: "site/content/cost-of-ownership/_index.md"
        label: "Cost Of Ownership"
        name: "costofownership"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Image Credit, name: imagecredit, widget: markdown, required: false}
          - label: Sections
            name: sections
            widget: list
            fields:
            - {label: Heading, name: heading, widget: string, required: false}
            - {label: Text, name: text, widget: markdown, required: false}
      - file: "site/content/cypher-notation/_index.md"
        label: "Cypher Notation"
        name: "cyphernotation"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Image Credit, name: imagecredit, widget: markdown, required: false}
          - label: Sections
            name: sections
            widget: list
            fields:
            - {label: Heading, name: heading, widget: string, required: false}
            - {label: Text, name: text, widget: markdown, required: false}
      - file: "site/content/digitizing-scores/_index.md"
        label: "Digitizing Scores"
        name: "digitizingscores"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Image Credit, name: imagecredit, widget: markdown, required: false}
          - label: Sections
            name: sections
            widget: list
            fields:
            - {label: Heading, name: heading, widget: string, required: false}
            - {label: Text, name: text, widget: markdown, required: false}
      - file: "site/content/finger-picks/_index.md"
        label: "Finger Picks Page"
        name: "finger-picks"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Image Credit, name: imagecredit, widget: markdown, required: false}
          - label: Sections
            name: sections
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: markdown}
              - {label: Image, name: imageUrl, widget: image}
              - {label: Caption, name: caption, widget: text}
      - file: "site/content/further-reading/_index.md"
        label: "Further Reading"
        name: "furtherreading"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Image Credit, name: imagecredit, widget: markdown, required: false}
          - label: Sections
            name: sections
            widget: list
            fields:
            - {label: Heading, name: heading, widget: string, required: false}
            - {label: Text, name: text, widget: markdown, required: false}
      - file: "site/content/general-mentions/_index.md"
        label: "General Mentions"
        name: "generalmentions"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Image Credit, name: imagecredit, widget: markdown, required: false}
          - label: Sections
            name: sections
            widget: list
            fields:
            - {label: Heading, name: heading, widget: string, required: false}
            - {label: Text, name: text, widget: markdown, required: false}
      - file: "site/content/guzheng-care/_index.md"
        label: "Guzheng Care"
        name: "guzhengcare"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Image Credit, name: imagecredit, widget: markdown, required: false}
          - label: Sections
            name: sections
            widget: list
            fields:
            - {label: Heading, name: heading, widget: string, required: false}
            - {label: Text, name: text, widget: markdown, required: false}
      - file: "site/content/guzheng-in-90-seconds/_index.md"
        label: "Guzheng in 90 Seconds"
        name: "guzhengin90"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Image Credit, name: imagecredit, widget: markdown, required: false}
          - label: Sections
            name: sections
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string, required: false}
              - {label: Anchor, name: anchor, widget: string, required: false}
              - {label: Text, name: text, widget: markdown, required: false}
